### ISSUE TITLE
Why no CMake or Makefile?

### ISSUE THREAD

**Issue by EntropyIncreaser** [creatorlxd/Space#2]
How can you build the project without CMake or Makefile?

**Comment by creatorlxd** [comment]
Because I compiler it on Windows.
I use Visual Studio to develop it.

**Comment by EntropyIncreaser** [comment]
@creatorlxd Hey, if you don't write a build file, how could other people work with you? The is a few people use VS.

**Comment by creatorlxd** [comment]
I always work on Windows,and I have not know how to write Makefile yet.
If I have time,I am sure I will learn that how to use the Makefile.
But now I am still a student that study in Senior High School.
I only have a few time to program,and that's why I want someone to join me.
Thank for your question.
It is very useful!!!

**Comment by ChillMagic** [comment]
@creatorlxd 
If you are using Visual Studio, you can provide the project file of VS.
EntropyIncreaser is wrong, many programmers are using VS.
Because the project is for Windows, so CMakeFile is not necessary.

And, good luck.
P.S. Why not use Chinese? I think you are all Chinese...

**Comment by creatorlxd** [comment]
呵呵，好吧！！！
问一下。
VS的项目文件具体是什么？
我不想把一大坨无用的文件都传上来！
谢了

**Comment by ChillMagic** [comment]
@creatorlxd 工程文件就是工程目录（工程目录一般在解决方案目录里面）下的_.vcxproj（或者_.vcxproj.*），清理一下解决方案，打开工程目录，把那些复制出来就行了。。

**Comment by creatorlxd** [comment]
@ChillMagic 也就是说只要传一下.vcxproj文件就行了？
谢了！！！

**Comment by ChillMagic** [comment]
@creatorlxd  具体情况的话，只要把那些文件拷贝出来，看看能否正常打开即可。

**Comment by EntropyIncreaser** [comment]
@ChillMagic @creatorlxd clion用户心里苦

**Comment by ChillMagic** [comment]
@EntropyIncreaser  Clion的话用过(在Linux下开发通用C++程序就是用的Clion)，感觉就是不如VS用起来舒服、、而且Clion是收费的，VS有社区版，免费。

另外。。这个项目明显就是把source里面的cpp当做source，把source里面的h当做include嘛。。手写个CMakeLists就行了嘛。。

**Comment by EntropyIncreaser** [comment]
@ChillMagic 然而还有很多用codeblocks的，拿vsproj岂不只能vs来写

**Comment by ChillMagic** [comment]
@EntropyIncreaser  Code::Blocks不大方便吧。。。小项目倒是挺好用的。。。
另外像这种Windows程序用VS原生支持是最好的。

**Comment by ChillMagic** [comment]
@creatorlxd 对了，GitHub有个.gitignore文件，你设置GitHub的项目，可以调整忽略的文件。设置成忽略Windows Visual Studio相关文件，这样直接把工程建在GitHub上传目录上面，它会自动忽略了。

**Comment by creatorlxd** [comment]
好吧。
不过我还是不咋么会玩.gitgnore
所以我还是把.vcproj和.vcxproj.filters都传一下吧！！！
