### ISSUE TITLE
请写README.MD

### ISSUE THREAD

**Issue by Glavo** [creatorlxd/Space#8]
如题。

另外，我应该如何构建它呢？请不要只使用vs的项目文件来配置

**Comment by ChillMagic** [comment]
您好！
目前，本项目只支持Visual C++编译器。

开发者是 @creatorlxd  ，其使用Visual Studio 2015进行开发。
实际上并没有通过GCC等编译器的编译。

关于构建问题，只要将 ```./include``` ```./DXSDK/Include``` 目录include，并增加 ```./DXSDK/Lib``` 的库引用，将```./source```目录作为编译的文件，即可通过编译。
